on: push
jobs:
  main:
    runs-on: cp-ubuntu-amd64-1core-1gb
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: cp-sandbox-nicholas-farl059
    steps:
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - run: gcloud projects describe "$PROJECT_ID"
